/**
 * @type {import('@remix-run/dev/config').AppConfig}
 */
module.exports = {
  appDirectory: "app",
  assetsBuildDirectory: "public/build",
  devServerPort: 8002,
  ignoredRouteFiles: [".*"],
  publicPath: "/build/",
  serverBuildPath: "app/server/build/index.js",
  serverDependenciesToBundle: [
    "webnative",
    "blockstore-datastore-adapter",
    "@chainsafe/is-ip",
    "datastore-core",
    "datastore-core/errors",
    "datastore-core/memory",
    "datastore-level",
    "ipfs-repo",
    "ipfs-repo-migrations",
    "it-pushable",
    "it-sort",
    "keystore-idb/aes/index.js",
    "keystore-idb/config.js",
    "keystore-idb/types.js",
    "keystore-idb/rsa/index.js",
    "keystore-idb/utils.js",
    "keystore-idb",
    "@libp2p/interface-keys",
    "@libp2p/peer-id",
    "@libp2p/interface-peer-id",
    "@libp2p/logger",
    "mortice",
    "@multiformats/multiaddr",
    "p-queue",
    "p-timeout",
    "sort-keys",
    "wnfs",
  ],
};
